<?php
    /* Template Name: Aviso de Privacidad */ 
    get_header();
?>

<section id="candado" class="template-section padding-50">

</section>

<section id="aviso" class="template-section">
    <div class="contenedor">
       
       
        <h1>Aviso de privacidad</h1>
        <p>De conformidad con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, previo al tratamiento de sus datos personales, en su calidad de titular de los mismos, se pone a su disposición nuestro aviso de privacidad.</p>
        
        <p>Magna Carta Lex es una firma de abogadas y abogados que procura garantizar la privacidad y el derecho a la autodeterminación informativa de las personas, a través de la protección de los datos personales en su posesión, y, para todos los efectos atinentes al presente aviso de privacidad, se señala como domicilio el ubicado en Torre World Trade Center CDMX, Montecito 38, piso 32, oficina 7, colonia Nápoles, demarcación territorial Benito Juárez, Ciudad de México, código postal 03810, Estados Unidos Mexicanos, con dirección de correo electrónico <a href="mailto:postandprivacymaster@magnacartalex.com" target="_top"><b>postandprivacymaster@magnacartalex.com</b></a>; lo anterior en específico para lo dispuesto en las fracciones III y IV del artículo 16 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, referentes al acceso, rectificación, cancelación, oposición y/o limitación de cualquier cuestión concerniente al uso y/o divulgación de sus datos personales.</p>
        
        <p>Como regla general, tal cual lo preceptúa el artículo 19 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, Magna Carta Lex se compromete a establecer y mantener medidas de seguridad, administrativas, técnicas y físicas, que permitan proteger sus datos personales contra daño, pérdida, alteración, destrucción y contra su uso, acceso o tratamiento no autorizados. De igual forma, Magna Carta Lex se compromete a guardar la debida confidencialidad mencionada en el artículo 21 de la aludida ley y a abstenerse de compartir sus datos personales con personas ajenas a nuestra firma de abogadas y abogados, que no se comprometan, a su vez, a tratarlos en la forma acordada y consentida, salvo por lo que respecta a las hipótesis indicadas en el artículo 4 del cuerpo normativo de referencia, correspondientes a la protección a la seguridad nacional, al orden público, a la seguridad pública, a la salud pública y a los derechos de terceros, y salvo por lo que atañe a las excepciones previstas en la propia ley. Asimismo, de conformidad con el artículo 6 del ordenamiento jurídico en cita, Magna Carta Lex observará los principios de licitud, información, calidad, finalidad, lealtad, proporcionalidad y responsabilidad en el tratamiento de sus datos personales.</p>
        
        <p>Usted tiene en todo momento el derecho a oponerse al tratamiento, conforme al presente aviso de privacidad, de sus datos personales. Si no lo hace, o hasta en tanto lo haga, como lo establece el artículo 8 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, se entiende que consciente tácitamente el tratamiento de sus datos personales con base en lo dispuesto en este aviso de privacidad.</p>
        
        <p>En esa tesitura, usted puede revocar en cualquier momento el consentimiento expreso o tácito para el tratamiento de sus datos personales. Por lo que, de acuerdo con los artículo 8 y 16, fracciones III y IV, de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, hacemos de su conocimiento, que, salvo por lo que respecta a las excepciones previstas en la propia ley, basta con que usted, o, en su caso, su represente legal, envíen un correo electrónico a <a href="mailto:postandprivacymaster@magnacartalex.com" target="_top"><b>postandprivacymaster@magnacartalex.com</b></a>, para que, cumpliendo con lo que resulte aplicable de lo señalado por los artículos 28, 29 y 31 del multicitado ordenamiento jurídico, tengan acceso, rectifiquen, cancelen, se opongan y/o limiten cualquier cuestión concerniente al uso y/o divulgación de sus datos personales. Además, de conformidad con el artículo 11 de la susodicha ley, cuando los datos de carácter personal hayan dejado de ser necesarios para el cumplimiento de las finalidades previstas en este aviso de privacidad y en las disposiciones legales aplicables, serán cancelados; asimismo, después de setenta y dos meses desde que se presente el incumplimiento, se eliminará de nuestras bases de datos la información relativa al incumplimiento de obligaciones contractuales.</p>
        
        <p>Los datos personales que de usted como titular de los mismos podríamos obtener, usar, almacenar, y, en su caso, divulgar, según sea el caso, teniendo acceso, manejándolos, aprovechándolos, transfiriéndolos o disponiendo de ellos, son:</p>
        
        <p>•	Datos de identidad, como, entre otros, nombre, nacionalidad, lugar de nacimiento, fecha de nacimiento, domicilio particular, número de teléfono fijo particular, número de teléfono celular particular, número de fax particular, correo electrónico particular, cuenta o perfil particular en red social o plataforma electrónica o cibernética y/o foto.</p>
        <p>•	Datos escolares, como, entre otros, trayectoria educativa, título, afiliación, número de cédula profesional, especialidad, reconocimiento y/o certificado.</p>
        <p>•	Datos laborales, como, entre otros, puesto, referencia laboral, curriculum vitae, domicilio laboral, número de teléfono fijo laboral, número de teléfono celular laboral, número de fax laboral, correo electrónico laboral y/o cuenta o perfil laboral en red social o plataforma electrónica o cibernética.</p>
        <p>•	Datos de facturación y/o financieros, como, entre otros, domicilio fiscal, clave del Registro Federal de Contribuyentes, entidad a la que se realizará el cargo, información concerniente a la cuenta bancaria y/o información referente a la forma o método de pago.</p>
        
        
        <p>Estos datos, según sea al caso, podrán utilizarse, por ejemplo, para controlar el acceso a nuestras instalaciones o por cuestiones de seguridad; para control y gestiones internas y comunicaciones entre los miembros de nuestra firma de abogadas y abogados, como, por ejemplo, respecto al estado de asuntos o de situaciones específicas de asuntos a su cargo o dentro de su responsabilidad o representación o interés; para contestar dudas, responder comentarios o atender quejas o consultas en nuestro sitio web o en nuestro blog o en nuestras redes sociales o plataformas electrónicas o cibernéticas o por correo electrónico o teléfono o mensajería instantánea u otro medio análogo; para formar o dar seguimiento a vínculos contractuales; para la facturación de los productos o servicios o cuestiones relacionadas; para proveer servicios de representación, autorización o asesoría legal o jurídica o académica; para realizar los trámites necesarios para satisfacer los servicios de representación, autorización o asesoría legal o jurídica o académica, así como contactar peritos o gestores o figuras análogas; para contactarla o contactarlo; para mantenernos en contacto con usted; para brindarle información de nuestros productos o servicios; para enviarle cotizaciones sobre nuestros productos o servicios o dar seguimiento a las mismas; para informarle el estado de alguna situación particular o el estado de los asuntos llevados en su nombre o representación; para entablar un contacto con usted y considerarla o considerarlo o dar seguimiento respecto a un proceso de reclutamiento o selección de personal; para enviarle información general o relacionada con nuestras áreas de practica o ejercicio o de interés o de interés público o particular o sobre nuestros productos o servicios; para, cuando usted dé clic en “Suscribirme”, suscribirla o suscribirlo a nuestro blog; para agregarla o agregarlo a nuestras redes sociales o plataformas electrónicas o cibernéticas y enviarle información o retransmitir o replicar la información que usted agregue a sus redes sociales o plataformas electrónicas o cibernéticas; para realizar estudios de mercado y la evaluación de nuestros productos y servicios; para fines estadísticos o de calidad en los productos o servicios; para enviarle promociones; para invitarla o invitarlo a eventos académicos, jurídicos, públicos, de beneficencia o sociales; para cuestiones de relaciones públicas; para confirmar o corregir su información, a fin de garantizarle la mejor atención personalizada y la mejor calidad en los productos o servicios; para efectos del mejoramiento de los productos o servicios, o un mejor manejo de la información o una mejor comunicación; para retransmitirle invitaciones de terceras personas o instituciones que creamos podrían ser de su interés; para, de ser necesario, informarle sobre los cambios al presente aviso de privacidad; o para cuestiones análogas a las señaladas.</p>
        
        <p>Magna Carta Lex se abstendrá de revelar información a compañías que pretendan venderle productos o servicios, como por ejemplo las de catálogos o las de multinivel o de esquema piramidal, o a aquellas cuyos productos o servicios no estén relacionados ni sean compatibles con nuestros productos o servicios o nuestras áreas de práctica o de ejercicio, y si se transmitiese información a personas o entidades ajenas a nuestra firma de abogadas y abogados, sería sola y exclusivamente en caso de que fuese necesaria para satisfacer principalmente vínculos jurídicos, sociales, contractuales o profesionales o para defender derechos o cumplir obligaciones en relación con los mismos, o, sobre todo, en aquellos casos donde usted hubiese dado su consentimiento previo.</p>
        
        <p>Magna Carta Lex puede estar haciendo uso de diversas tecnologías para mejorar la eficiencia de su sitio web o de los registros del servidor o “web beacons”, por virtud de la obtención no personal de información que se da por su simple uso e interacción, la cual puede consistir en protocolos de internet, o ser referente a su navegador, sistema operativo, ubicación o movimientos dentro del sitio web. Estos datos se podrán recabar con el propósito de, por ejemplo, generar estadísticas relativas al tiempo que pasa en el sitio web o a la forma en que pudo haber llegado al mismo.</p>
        
        <p>Para el efecto del mejoramiento de nuestro sitio web podremos estar haciendo también uso de las denominadas “cookies”, que son pequeños archivos de texto no personal que nuestro sitio web envía a su computadora mientras lo visita, los cuales quedan almacenados en su disco duro, permitiendo que la siguiente vez que visite nuestro sitio web, se utilice la información almacenada en la cookie para facilitarle su uso y mejorar su experiencia. Usted puede configurar su navegador para que le avise sobre las cookies, de manera que pueda aceptarlas, o, en su caso, rechazarlas. </p>
        
        <p>De acuerdo con la fracción VI del artículo 16 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, el presente aviso de privacidad podrá ser modificado, y las modificaciones serán hechas de su conocimiento por el mismo medio en que se puso a su disposición, quedando incólumes sus derechos a tener acceso, a rectificar, a cancelar, a oponerse y/o a limitar cualquier cuestión concerniente al uso y/o divulgación de sus datos personales, como lo disponen los artículo 8 y 16, fracciones III y IV, del mismo cuerpo normativo, lo que además es de orden público y de observancia general en toda la república mexicana.</p>
        
        <p>En caso de tener dudas y/o comentarios en relación con el presente aviso de privacidad, le reiteramos que puede escribirnos a la dirección de correo electrónico <a href="mailto:postandprivacymaster@magnacartalex.com" target="_top"><b>postandprivacymaster@magnacartalex.com</b></a>, donde con gusto le atenderemos. Gracias.</p>
        
    </div>
</section>

<?php 
    get_footer();
?>